FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5679 --disabled-password --gecos "" notificationui-user && chown -R notificationui-user:notificationui-user /app
USER notificationui-user

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

ENV DOTNET_NUGET_SIGNATURE_VERIFICATION=false

RUN pwd
RUN ls
COPY . .
RUN dotnet restore "bbt.service.notification-profile.ui/bbt.service.notification.ui.csproj"
WORKDIR "/src/bbt.service.notification-profile.ui"
RUN pwd
RUN ls
RUN dotnet build "bbt.service.notification.ui.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "bbt.service.notification.ui.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
RUN pwd
RUN ls
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://*:5000
ENTRYPOINT ["dotnet", "bbt.service.notification.ui.dll"]
